### ISSUE TITLE
What is the variabele n_t?

### ISSUE THREAD

**Issue by kroese** [bitromortac/lndmanage#135]
In the code for analyze-fees there is a variabele defined:

`"n_t": 4 / 7`

that is used for calculating the optimal fee. 

What is its purpose? I think the 7 stands for 7 days, but have no clue about the 4. 

I'm running the script on a daily schedule instead of the default (weekly), so Im a bit cautious when I see something divided by 7 in the code.

**Comment by bitromortac** [comment]
This factor influences the base fee. It is the equivalent to the target volume per week per channel in case of the fee rate updates. You have the following pairs in fee rate optimization (number of forwardings, base fee) and (amount volume, fee rate), where I regard them to be independent of each other.
This factor here influences the base fee, which means that a target of 4 forwardings per week is regulated for. If the number of forwardings per channel is less than 4, the base fee decreases, if it is higher than 4, it increases. You can use it to get more fees out of microtransaction usage, but the parameter is chosen arbitrarily. Right now it is not exposed as a cli parameter, which could be done.

**Comment by kroese** [comment]
Thanks for the explanation, I use zero base fees for all channels, so this parameter is not even applicable to my case then.
