### ISSUE TITLE
Error with protobuff

### ISSUE THREAD

**Issue by zx9r** [bitromortac/lndmanage#142]
Building from current github master. Running lndmage throws the following error:

> (venv) alberto@alberto-MS-7B22:~/lndmanage$ lndmanage status
> Traceback (most recent call last):
>   File "/home/alberto/lndmanage/venv/bin/lndmanage", line 5, in <module>
>     from lndmanage.lndmanage import main
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/lndmanage/lndmanage.py", line 11, in <module>
>     from lndmanage.lib.fee_setting import FeeSetter, optimization_parameters
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/lndmanage/lib/fee_setting.py", line 12, in <module>
>     from lndmanage.lib.forwardings import ForwardingAnalyzer
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/lndmanage/lib/forwardings.py", line 9, in <module>
>     from lndmanage.lib.node import LndNode
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/lndmanage/lib/node.py", line 15, in <module>
>     import lndmanage.grpc_compiled.lightning_pb2 as lnd
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/lndmanage/grpc_compiled/lightning_pb2.py", line 33, in <module>
>     _descriptor.EnumValueDescriptor(
>   File "/home/alberto/lndmanage/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
>     _message.Message._CheckCalledFromGeneratedFile()
> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> 
> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
> 

My protoc version is:

> $ python -m grpc_tools.protoc --version
> libprotoc 3.21.6
> 

I rebuilt grpc running `./build_grpc.sh` Rebuilding worked well with no errors but when running lndmanage again same error occurrs.

Installed lib dependencies are:

> $ pip freeze
> googleapis-common-protos==1.58.0
> grpcio==1.51.3
> grpcio-tools==1.51.3
> lndmanage @ file:///home/alberto/lndmanage
> networkx==3.0
> numpy==1.24.2
> protobuf==4.22.0
> Pygments==2.14.0

**Comment by bitromortac** [comment]
Hey, the issue is that the current `setup.py` allows installation of `"protobuf>=4.0"`, which should be `"protobuf>=3.0,<4.0"`. You could try https://github.com/bitromortac/lndmanage/pull/141, it has updated dependencies, will merge that soon.

**Comment by zx9r** [comment]
Thank you. I downgraded protobuf and also removed the np.warnings and it is working now

**Comment by bitromortac** [comment]
Fixed by #141.
