### ISSUE TITLE
Key error while updating fees

### ISSUE THREAD

**Issue by kroese** [bitromortac/lndmanage#144]
```
Traceback (most recent call last):
  File "/root/lndmanage/lndmanage.py", line 5, in <module>
    main()
  File "/root/lndmanage/lndmanage/lndmanage.py", line 663, in main
    asyncio.run(_main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/lndmanage/lndmanage/lndmanage.py", line 603, in _main
    await parser.run_commands(lndnode, args)
  File "/root/lndmanage/lndmanage/lndmanage.py", line 584, in run_commands
    feesetter.set_fees(
  File "/root/lndmanage/lndmanage/lib/fee_setting.py", line 152, in set_fees
    channel_fee_policies, stats = self.new_fee_policies(init)
  File "/root/lndmanage/lndmanage/lib/fee_setting.py", line 223, in new_fee_policies
    cumul_fee_rate += self.channel_fee_policies[
KeyError:'xxxxxxxxxxxxxxxxxxxxxxxxxxx:1'
```

I already tried clearing the cache, but it made no difference.

**Comment by bitromortac** [comment]
It looks like an not all open channels appear in `lncli feereport`. Hope the error solved itself, but if it happens again, this would be the first I would check.

**Comment by kroese** [comment]
I still have this issue after more than a week. Haven't been able to update my fees ever since. I'm running the latest version of LND, so obviously this situation can happen in practice. 

Could you please modify the code to ignore that channel, because I dont care if 1 channel cannot update fees, its better than just aborting the script.

**Comment by bitromortac** [comment]
Could you check whether the unknown channel appears in `lncli feereport`?

**Comment by kroese** [comment]
If the `KeyError` value refers to a `channel_point`, then I don't see that channel_point in `lncli feereport`.

**Comment by kroese** [comment]
I looked up which channel it actually is.. and indeed it has some special circumstances.

First off, when I created this channel I set the opening fee too low, so it was pending for well over a month in the memory pool. 10 days ago it finally got accepted in the chain, and that was when I started to get this problem. Also it seems it is not active at the moment (shows in red in Thunderhub).

**Comment by bitromortac** [comment]
It looks like that the channel is not operational because your peer has forgotten about the funding process (usually after 2 weeks of an unconfirmed opening). With the latest mempool situation, this happens quite often, ~see for instance this issue `https://github.com/lightningnetwork/lnd/issues/7426` and how to fix it~. I'll nevertheless supply a fix for that.

**Comment by kroese** [comment]
@bitromortac Thanks for the help, I totally forgot there was a limit of 2 weeks. I reported the problem in the linked issue.

**Comment by kroese** [comment]
This is not my lucky day.. First, I lost 5M sats by blindly following the instructions in that issue. And to make it even worse, it did not even solve my problem with managelnd, because now I simply get a different error:

```
/root/.venv/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/root/.venv/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
```

**Comment by bitromortac** [comment]
> This is not my lucky day.. First, I lost 5M sats by blindly following the instructions in that issue.

Sorry this happend, I didn't realize that it was not exactly your scenario.

> And to make it even worse, it did not even solve my problem with managelnd, because now I simply get a different error:

This is an issue in computing mean/median values for forwardings. #146 fixes the key error (it adds a better error message) and removes the warnings.

**Comment by kroese** [comment]
> Sorry this happend, I didn't realize that it was not exactly your scenario.

The first post is exactly my scenario, so it's absolutely not your fault. The misleading thing was that the steps listed a few posts down don't apply to the first post (because they are not for the one who created the channel, but for the other side). I should have read the posts in between more carefully.

> This is an issue in computing mean/median values for forwardings. #146 fixes the key error (it adds a better error message) and removes the warnings.

Great news, I will try it out!

**Comment by bitromortac** [comment]
Thank you. I'd like to invite you to join the LND [slack](https://lightning.engineering/slack.html), I'd be there to help with future problems interactively.
