### ISSUE TITLE
Request: New tag

### ISSUE THREAD

**Issue by kroese** [bitromortac/lndmanage#149]
The last tag (0.15) is from March, but since then were several commits with fixes.

Is it possible to create a new tag (0.16) that is up to date with the master?

**Comment by bitromortac** [comment]
I have created a PR for the new grpc proto files for lnd 0.16.4 (the current files still work with lnd 0.16.X and 0.17.X). Will tag a new version once https://github.com/bitromortac/lndmanage/pull/151 is merged.

**Comment by bitromortac** [comment]
I would still like to add https://github.com/bitromortac/lndmanage/pull/152, using the readonly macaroon by default before tagging a new version. Would that break anything for you? This would affect `openchannels` and `update-fees`, for which a new macaroon has to be baked via a script.

**Comment by kroese** [comment]
@bitromortac I already baked the macaroon and update my compose file, so Im ready to go!

**Comment by kroese** [comment]
@bitromortac Can you create the tag? (My automatic build script depends on it) Thanks in advance..

**Comment by bitromortac** [comment]
Tag is pushed, sorry for the delay, I wanted to test things more.

**Comment by kroese** [comment]
Unfortunately it still doesnt work, I should not have used the word tag I guess.

Because what I needed was a release (as that creates a tag+branch for 0.16.0 and I can pull that branch), like you did with the previous versions.
