### ISSUE TITLE
Raspbian does not yet include Python 3.6

### ISSUE THREAD

**Issue by gcomte** [bitromortac/lndmanage#22]
I'd like to run your awesome tool on my RaspiBolt, but Raspbian only ships with Python 3.5 as of now.

**Comment by bitromortac** [comment]
Thank you, Gabriel. One of the problems that I'm aware of are the format strings
`f"text {variable}"`, which are not supported before python 3.6. Those should be replaced with `"text {}".format(variable)`. At that moment I'm not yet sure if I should replace this everywhere in the code.

**Comment by gcomte** [comment]
Updating to Raspbian Buster fixes this.

Buster comes with python 3.7.3 . I am finally running lndmanage on my RaspiBolt! 🎉
