### ISSUE TITLE
Lots of "Unknown next peer somewhere in route."

### ISSUE THREAD

**Issue by th3geek** [bitromortac/lndmanage#33]
About 25% of my failures are coming from "Unknown next peer somewhere in route." and I realize this is likely an lnd problem, but I don't remember seeing this message before upgrading to 0.7.0 and searching around the lnd issues I don't see other people getting the same error. 

I guess the reason I'm asking here is... is that a message that lnd is returning and you're just displaying the message or is lndmanage trying to figure out the problem and it comes to the conclusion "Unknown next peer somewhere in route."? 

Doing a google search for that string only brings back a couple lnd results but have to do with eclair. 

Any insights?

**Comment by th3geek** [comment]
So I was watching lnd when this error happened (it's happening often) and here's the error it gives:

2019-07-15 01:14:55.516 [ERR] CRTR: Attempt to send payment 0fb526deaefe72d072c5dd442f6dbabfa7cc51982fc28cedc1298d24b680502d failed: FeeInsufficient(htlc_amt==1033717446 mSAT, update=(lnwire.ChannelUpdate) {

I don't see anything in lnd about "unknown next peer ..." when the error occurs.

**Comment by th3geek** [comment]
Weird. I kept looking at the lnd logs, and I do see instances of UnknownNextPeer, so guess I'll do a search for that and see what I get.

**Comment by bitromortac** [comment]
Thank you for reporting! I'll have a closer look in about 10 days when I'm back from holidays. Appreciate your bug hunting :)

**Comment by th3geek** [comment]
Great, Thank you. This program has saved me so much manual work...  I'm contemplating making a GUI frontend or ncurses or maybe just a shell script to automate channel maintenance a little bit.

Enjoy your vacation!
