### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by gehlm** [bitromortac/lndmanage#37]
$ ./lndmange.py rebalance --max-fee-sat 20 --max-fee-rate 0.00001 channel_id

should be...

$ ./lndmanage.py rebalance --max-fee-sat 20 --max-fee-rate 0.00001 channel_id

**Comment by bitromortac** [comment]
Correct, thank you! Fixed with a0d71ce789156e7e5c763c3c4cb1d91be6abc82a.
