### ISSUE TITLE
pkg-resources==0.0.0 should not be in requirements.txt

### ISSUE THREAD

**Issue by darwin** [bitromortac/lndmanage#5]
Getting this error when running pip install:
```
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 10))
```

I'm a python noob, google says:

https://stackoverflow.com/questions/40670602/could-not-find-a-version-that-satisfies-the-requirement-pkg-resources-0-0-0

**Comment by bitromortac** [comment]
Thank you for reporting!  This is fixed by ab60215f12d03a9ff7185bce5b759e7475fc15ef.

May I ask you if everything else worked for you so far?

**Comment by darwin** [comment]
Not really. I wanted to play with it on my VPS where is my lnd node located. So first step was to dockerize it, because I didn't want to bring python + all the deps to the host machine. I know you are using virtualenv which should be quite clean. But for me as a relatively inexperienced python user it is safer to keep all in a disposable docker than experimenting on the host machine directly.

Anyways, when running it in docker, I'm getting this error:
```
> lndmanage.sh status
Initializing node interface.
Initializing network graph.
Saved graph is too old. Fetching new one.
Traceback (most recent call last):
  File "/root/src/lndmanage.py", line 115, in <module>
    main()
  File "/root/src/lndmanage.py", line 87, in main
    node = LndNode()
  File "/root/src/lib/node.py", line 54, in __init__
    self.network = Network(self)
  File "/root/src/lib/network.py", line 26, in __init__
    self.cached_reading_graph_edges()
  File "/root/src/lib/network.py", line 45, in cached_reading_graph_edges
    nx.write_gpickle(self.graph, cache_graph_filename)
  File "</root/.venv/lib/python3.7/site-packages/decorator.py:decorator-gen-582>", line 2, in write_gpickle
  File "/root/.venv/lib/python3.7/site-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/src/lib/../cache/edges.gpickle'
```

**Comment by darwin** [comment]
btw. will send you a PR with that added docker support today

**Comment by darwin** [comment]
The issue went away (probably) when I mapped lndmanage/cache to host via a volume. Details in the PR #6
