### ISSUE TITLE
negative bf seems to block rebalance from happening

### ISSUE THREAD

**Issue by haukehess** [bitromortac/lndmanage#50]
I have an open channel to 1ML:

```
       cid          priv act    ub       cap        lb        rb    bf       fr        annotation                   alias           
666012675878748161   ✗    ✓  -1.00    800000    796357         0  -999 0.000999 ......................... 1ML.com node ALPHA....... 
```

Rebalancing it leads to

```
$ lndmanage rebalance 666012675878748161

Initializing node interface.
Initializing network graph.
Reading graph from file.
>>> Trying to rebalance channel 666012675878748161 with a max rate of 5e-05 and a max fee of 20 sat.
>>> Chunk size is set to 1.0.
>>> This is a dry run, nothing to fear.
>>> The channel status before rebalancing is lb:796357 sat rb:0 sat cap:800000 sat.
>>> Trying to change the local balance by -403643 sat.
    The expected unbalancedness target is 0.01 (respecting channel reserve), requested target is 0.00.
>>> There are 1 channels with which we can rebalance (look at logs).
>>> We will try to rebalance with them one after another.
>>> NOTE: only individual rebalance requests are optimized for fees:
    this means that there can be rebalances with less fees afterwards,
    so take a look at the dry runs first, i.e. without the --reckless flag,
    and set --max-fee-sat and --max-fee-rate accordingly.
    You may also specify a rebalancing strategy by the --strategy flag.
>>> Rebalancing can take some time. Please be patient!

Rebalance failure: Amount should not be negative! amt:-1716 sat

```

I guess the negative "bf" troubles the algorithm, but I have no idea why this is the only negative channel and what to do about it.

**Comment by bitromortac** [comment]
Thanks for reporting!
From the output I see that there is just one channel which is unbalanced in the other direction as the one you try to rebalance (`There are 1 channels with which we can rebalance (look at logs).`). From my experience, specifically also for the 1ML node this doesn't have much chance to succeed, as the 1ML node seems to be very unbalanced.

There are two things to add here. You see that there are inaccurate fees present in the listchannels command, this means that the channel is probably new and lnd hasn't updated its internal graph representation. You can try to delete the cache folder in ~/.lndmanage, or to try again later. Afterwards the peer fees should be correctly reflected.

The negative amount issue you see here, stems from a small inaccuracy in counterparty channel selection. Essentially this means, there is one counterparty channel, which is close to being balanced. In short, that channel shouldn't be even tried. This is known and I should fix it.

If you really want to force the 1ML node to get more balanced you can run with the flag `--allow-unbalancing` and `--chunksize 0.1` for example. Try it without the `--reckless` flag first.

Hope I could help you a bit.

**Comment by haukehess** [comment]
You are right, waiting helped. Now the bf to 1ML is 1000.
One more thing: where should I look for the logs as in "(look at logs)"? Or: how can I find out where to look for logs?

**Comment by bitromortac** [comment]
Yes that's not very clear :smile:. Look into ~/.lndmanage/lndmanage.log.

**Comment by haukehess** [comment]
Thanks for a great tool!

**Comment by haukehess** [comment]
Is "Encountered temporary channel failure" more than the observation that lightning network is still in its infancy?

**Comment by bitromortac** [comment]
It's the standard outcome of a single rebalancing trial :), yes most channels are very unbalanced.

**Comment by haukehess** [comment]
Sigh...
