### ISSUE TITLE
Receiving-rebalancing of multiple connected node channel not supported.

### ISSUE THREAD

**Issue by DrVecctor** [bitromortac/lndmanage#76]
I am aware that "The reason is that the last hop (channel) can't be controlled by us."
But I would argue that now, with MPP working, it actually does not matter which receiving channel receives the funds. So I suggest to treat multiple channels between the same nodes (at least in the incoming case) as one, and balance "the entireness" of channels. Certainly the user should be made aware of this, and be required to set some flag to acknowledge they understood this. But in my opinion multiple channels between the same nodes should be supported if possible.

**Comment by bitromortac** [comment]
Hey, yes I was thinking to somehow transition from a per channel basis to a per peer basis or to create an extra "listpeers", which aggregates the channels. I'll have to think a little bit more about it.
