### ISSUE TITLE
installation missing readline module

### ISSUE THREAD

**Issue by lockhartheavyindustries** [bitromortac/lndmanage#79]
When installing via pip to a MyNode, fails to run due to missing readline module. Works fine once installing module then starting again.

<img width="1136" alt="Screenshot 2020-07-25 10 30 05" src="https://user-images.githubusercontent.com/1934729/88462660-fbceb900-ce61-11ea-950a-ce3180616a2a.png">

**Comment by bitromortac** [comment]
Thanks for reporting this. I'll test it on python3.7. It's a bit strange as I was of the impression that readline is part of the standard library.
