### ISSUE TITLE
output of rebalance with "max-fee-sat" implies it is both sat and msat

### ISSUE THREAD

**Issue by onyxcoyote** [bitromortac/lndmanage#82]
I believe one of the log outputs is incorrect reporting 1000 sat and 1000 msat for the same input parameter.

lndmanage rebalance $CHAN --max-fee-sat 1000
> .. with a max rate of 0.009 and a max fee of **1000 sat**.
>  Channel is too expensive. Fee: 300000.000000 msat, requested max fee: **1000.000000 msat**

The expected behavior is that it refers to either sat or msat but not both.

**Comment by bitromortac** [comment]
Oh yes, that's right, will fix it! Thank you!

**Comment by bitromortac** [comment]
Fixed by 593ade58b0b377f9e9f204272f051ccb1e3eaf21, thanks again!
