### ISSUE TITLE
problem installing lndmanage python 3.8.6

### ISSUE THREAD

**Issue by emplexity** [bitromortac/lndmanage#83]
The installation process of lndmanage on Ubuntu 16.04 with python 3.8.6 installed goes in error at its last step: 
python3 -m pip install lndmanage
see the attached screen dump with the error messages produced. 
It looks  similar to the issue #62. I have applied the proposed workarounds without success.
[lndmanageInstIssue.txt](https://github.com/bitromortac/lndmanage/files/5395815/lndmanageInstIssue.txt)

**Comment by 3nprob** [comment]
You need `libffi-dev`: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul
